---
- hosts: controllers

  # List of roles to apply to the controllers, in the order in which they will run.
  # NOTE: These and their default configurations can be found in the "roles/"
  #       directory.

  roles:
    - role: trinity/init
      tags: init

    - role: trinity/sensu-client
      tags: monitoring

    - role: trinity/local_repo
      tags: local_repo
      when: local_install

    - role: trinity/trix-tree
      tags: trix-tree

    - role: trinity/repos
      repos:
        - repo: '{{ trix_local_repo_baseurl }}'
          name: '{{ trix_local_reponame }}'
      tags: local_repo
      when: local_install

    - role: trinity/repos
      repos:
        - repo: epel-release
        - repo: '{{ luna_repo }}'
      tags: repos

    - role: trinity/cv_support
      tags: cv_support

    - role: trinity/packages
      tags: packages

    - role: trinity/tunables
      tags: tunables

    - role: trinity/hostname
      tags: hostname

    - role: trinity/firewalld
      tags: firewalld

    - role: trinity/chrony
      tags: chrony

    - role: trinity/rdma-centos
      tags: rdma-centos

    - role: trinity/ssh
      tags: ssh

    - role: trinity/nfs
      nfs_rpccount: 256
      nfs_enable_rdma: false
      nfs_export_shared: true
      nfs_export_home: true
      nfs_exports_path: '{{ trix_local }}/etc/exports.d'
      tags: nfs

    - role: trinity/ssl-cert
      ssl_cert_country: 'NL'
      ssl_cert_locality: 'Amsterdam'
      ssl_cert_organization: 'ClusterVision Solutions B.V.'
      ssl_cert_state: 'Noord Holland'
      ssl_cert_altname: '{{ trix_ctrl_hostname }}.{{ trix_domain }}'
      ssl_cert_days: '3650'
      tags: ssl-cert

    - role: trinity/bind
      bind_db_path: '{{ trix_local }}/var/lib/named'
      bind_dnssec_enable: "no"
      bind_dns_forwarders:
        - '8.8.8.8'
        - '8.8.4.4'
      resolv_server: '{{ trix_ctrl_ip }}'
      tags: bind

    - role: trinity/mariadb
      mariadb_db_path: '{{ trix_local }}/var/lib/mysql'
      tags: mariadb

    - role: trinity/openhpc
      nfs_exports_path: '{{ trix_local }}/etc/exports.d'
      when: enable_openhpc
      tags: openhpc

    - role: trinity/slurm
      slurm_ctrl: '{{ trix_ctrl_hostname }}'
      slurm_ctrl_ip: '{{ trix_ctrl_ip }}'
      slurm_ctrl_list: '{{ trix_ctrl1_hostname }},{{ trix_ctrl2_hostname }}'
      slurm_conf_path: '{{ trix_shared }}/etc/slurm'
      slurm_spool_path: '{{ trix_local }}/var/spool/slurm'
      munge_conf_path: '{{ trix_shared }}/etc/munge'
      slurmdbd_sql_user: 'slurm_accounting'
      slurmdbd_sql_db: 'slurm_accounting'
      tags: slurm
      when: workload_manager == "slurm"

    - role: trinity/slurm-sbank
      tags: slurm, sbank
      when: workload_manager == "slurm"

    - role: trinity/luna
      luna:
        cluster:
          frontend_address: '{{ trix_ctrl_ip }}'
          path: '{{ trix_local }}/luna'
          named_include_file: '{{ trix_local }}/etc/named.luna.zones'
          named_zone_dir: '{{ trix_local }}/var/lib/named'
          lweb_num_proc: 4
        dhcp:
          conf_path: '{{ trix_local }}/etc/dhcp'
          network: '{{ trix_domain }}'
          start_ip: '{{ trix_cluster_dhcp_start }}'
          end_ip: '{{ trix_cluster_dhcp_end }}'
        networks:
          - name: '{{ trix_domain }}'
            ip: '{{ trix_cluster_net }}'
            prefix: '{{ trix_cluster_netprefix }}'
            ns_ip: '{{ trix_ctrl_ip }}'
      tags: luna

    - role: trinity/rsyslog
      syslog_listeners:
        - name: default
          proto: tcp
          port: 514
        - name: default
          proto: udp
          port: 514
      syslog_file_template_rules:
        - name: controllers
          type: string
          content: '/var/log/cluster-messages/%HOSTNAME%.messages'
          field: '$fromhost-ip'
          criteria: startswith
          rule: '{{ trix_cluster_net.split(".")[:trix_cluster_netprefix//8]|join(".") }}'
      tags: rsyslog

    - role: trinity/wrapup
      tags: wrapup

    - role: trinity/telegraf
      tags: monitoring
      influxdb_server: "{{ trix_ctrl_ip }}"

    - role: trinity/rabbitmq
      tags: monitoring

    - role: trinity/sensu-server
      tags: monitoring

    - role: trinity/influxdb
      tags: monitoring
      influxdb_server: "{{ trix_ctrl_ip }}"

    - role: trinity/grafana
      tags: monitoring
      ldap_auth: true
      enable_ssl: true
      ssl_certificate: "{{ ssl_cert_path }}/{{ ansible_fqdn }}.crt"
      ssl_certificate_key: "{{ ssl_cert_path }}/{{ ansible_fqdn }}.key"
