---
# Install additional packages and tunables

- name: Install prereq packages
  yum:
    name: "{{ packages_packages }}"
    state: present
  tags: install-only

- name: Install additional packages
  yum:
    name: "{{ tunables_packages }}"
    state: present
    enablerepo: powertools
  tags: install-only
  when: ansible_distribution == "Rocky"

- name: Install additional packages
  yum:
    name: "{{ tunables_packages }}"
    state: present
#    enablerepo: rhel-7-server-optional-rpms
  tags: install-only
  when: ansible_distribution == "RedHat"

- name: Install additional packages
  yum:
    name: "{{ tunables_packages }}"
    state: present
  tags: install-only
  when: ansible_distribution == "CentOS"

- name: Install Infiniband support
  yum:
    name: "@Infiniband support"
    state: present
  when: install_infiniband
  tags: install-only

- name: Install Infiniband support (compat)
  yum:
    name: compat-opensm-libs
    state: present
  when: install_infiniband
  tags: install-only

- name: Enable haveged service
  service:
    name: haveged
    enabled: yes

- name: Start haveged service
  service:
    name: haveged
    state: started
  when: ansible_connection not in 'lchroot'
