---

- name: Install Influxdata repo
  yum_repository:
    name: influxdata-el7
    baseurl: "{{ influxdata_repo }}"
    description: Influxdata
    gpgkey: https://repos.influxdata.com/influxdb.key

- name: Install telegraf
  yum:
    name: telegraf
    state: present

- name: Configure default telegraf.conf
  template:
    src: telegraf.conf.j2
    dest: /etc/telegraf/telegraf.conf
  notify: restart telegraf

- name: Configure TrinityX telegraf configurations
  template:
    src: trinityx.conf.j2
    dest: /etc/telegraf/telegraf.d/trinityx.conf
  notify: restart telegraf

- name: Place telegraf sudoers file
  template:
    src: sudo.telegraf.j2
    dest: /etc/sudoers.d/telegraf
 
- name: Place telegraf service config
  template:
    src: telegraf.service.j2
    dest: /usr/lib/systemd/system/telegraf.service
 
- name: Start telegraf
  systemd:
    name: telegraf
    daemon_reload: yes
    state: started
    enabled: "yes"

