---

- name: Create trinity/ohpc dir for opt link to point at
  file:
    path: '{{ trix_ohpc }}'
    owner: root
    group: root
    state: directory
    mode: '0755'
  when: '"controllers" in group_names'

- name: Create link so openhpc ends up on /trinity filesystem
  file:
    src: '{{ trix_ohpc }}'
    path: /opt/ohpc
    owner: root
    group: root
    state: link
  when: ansible_connection not in 'chroot' and "controllers" in group_names


- name: Install ohpc-release
  yum:
    name: https://github.com/openhpc/ohpc/releases/download/v2.4.GA/ohpc-release-2-1.el8.x86_64.rpm
    state: installed
    disable_gpg_check: yes

- name: Ensure conflicting rpms from legacy TrinityX are not installed
  yum:
    name:
      - pdsh
      - environment-modules
    state: removed

- name: Install ohpc-base
  yum:
    name: ohpc-base
    state: installed
  when: ansible_connection not in 'chroot' and "controllers" in group_names and ansible_distribution == "CentOS"

- name: Install ohpc-base
  yum:
    name: ohpc-base
    state: installed
    enablerepo: rhel-7-server-optional-rpms
  when: ansible_connection not in 'chroot' and "controllers" in group_names and ansible_distribution == "RedHat"

- name: Install ohpc-base-compute
  yum:
    name: ohpc-base-compute
    state: installed
  when: ansible_connection not in 'chroot' and "controllers" in group_names

- name: Install lmod dependencies on non-controller nodes
  yum:
    name:
      - lua-filesystem
      - lua-posix
    enablerepo: powertools
    state: installed
  when: ansible_connection in 'chroot' or "controllers" not in group_names

- name: Create symlinks for pdsh and pdcp
  file:
    dest: "/usr/bin/{{ item }}"
    src: "/opt/ohpc/admin/pdsh/bin/{{ item }}"
    state: link
    force: yes
    follow: no
  with_items:
    - pdsh
    - pdcp

- name: Install lmod-ohpc
  yum:
    name: lmod-ohpc
    state: installed
  when: ansible_connection in 'chroot' or "controllers" not in group_names

- name: Install profile for modules
  template:
    src: z_trinityx.sh.j2
    dest: /etc/profile.d/z_trinityx.sh

- name: Update NFS exports
  template:
    src: OHPC_exports.j2
    dest: '{{ nfs_exports_path }}/ohpc.exports'
  when: primary | default(True) and ansible_connection not in 'chroot'
  notify:
    - Export NFS

- file:
    src: '{{ nfs_exports_path }}/ohpc.exports'
    dest: '/etc/exports.d/ohpc.exports'
    state: link
    force: "yes"
  when: primary | default(True) and ansible_connection not in 'chroot'
  notify:
    - Export NFS
