---
# vars file for cv_support

trix_tools:
  - 'trix-diag'
  - 'slurmibtopology.sh'
  - 'request-remote-assistance'
  - 'request-remote-assistance-automated'

cv_support_packages:
  - python2-libs
  - tigervnc-server
  - firefox
  - icedtea-web
  - icewm

project_id: '000000'
trix_version: '0'
ha: 'False'
trix_ctrl_ip: '127.0.0.1'
