---

sensu_user: sensu
sensu_group: sensu

sensu_client_gems:
  - name: sensu-plugins-chrony
    state: present
  - name: sensu-plugins-cpu-checks
    state: present
  - name: sensu-plugins-disk-checks
    state: present
  - name: sensu-plugins-dns
    state: present
    yumprereq:
      - gcc-c++
      - make
  - name: sensu-plugins-entropy-checks
    state: present
  - name: sensu-plugins-ipmi
    state: present
  - name: sensu-plugins-load-checks
    state: present
  - name: sensu-plugins-memory-checks
    state: present
  - name: sensu-plugins-network-checks
    state: present
  - name: sensu-plugins-pacemaker
    state: present
  - name: sensu-plugins-ssl
    state: present
  - name: sensu-plugins-systemd
    state: present
